### ISSUE TITLE
Prop "title" is ignored

### ISSUE THREAD

**Issue by kilya11** [react-component/checkbox#104]
If I pass the `title` as a prop to the `Checkbox` component, it will be removed before passing it to the HTML attribute `title`.
Like the `data-*`, `aria-*` and `role` attributes it should be passed over to the HTML.

E.g.
`<Checkbox title="Dr. Prof." />`
should be mapped to
`<input type="checkbox" title="Dr. Prof." />`.

**Comment by zzkkui** [comment]
this pr why not merged

**Comment by yoyo837** [comment]
#218 Is that better?

**Comment by yoyo837** [comment]
Or please handle the conflict.

**Comment by zzkkui** [comment]
> #218 Is that better?

sure，I find it now
