### ISSUE TITLE
Does not work with browser-sync

### ISSUE THREAD

**Issue by queimadus** [react-component/checkbox#13]
[Browser sync](https://github.com/Browsersync/browser-sync) injects a extra `blur(); focus();` to checkboxes and radios at the `addEventListener` level.
Resulting in the following sequence of events:
```js
<Checkbox 
  checked={false}
  onBlur={e => console.log("blur", e.target.checked)}
  onFocus={e => console.log("focus", e.target.checked)}
  onChange={e => console.log("focus", e.target.checked)}
/>

- focus,  false
- blur,   true (added by browsersync)
- focus,  false (added by browsersync)
- change, false
```

When the onChange is called the `e.target.chacked` is no longer `true`and thus the checkbox never toggles its state. 

This only fails in `1.3.4` since the addition of `onBlur` and `onFocus` that change the component state.
If I comment out the `setState` lines from `onBlur` and `onFocus` it works correctly (albeit isFocused support is lost ofc)

**Comment by queimadus** [comment]
Codepen reproducing the issue:
http://codepen.io/anon/pen/PNvjxq

**Comment by ryannealmes** [comment]
I am trying to leverage this control in the [react-slingshot](https://github.com/coryhouse/react-slingshot) framework. 

It seems like a similar issue to this is cropping it's head up. I have forked the [repo](https://github.com/ryannealmes/react-slingshot/tree/rc-checkbox) for slingshot and modified it to include the rc-checkbox control in the App component. If you do an `npm instal`l, `npm start` and try click the checkbox you will see that it doesn't change.

Any ideas on how to fix this? I have gone down this rabbit hole, but had no luck.

Happy to help out more if needed.

**Comment by kossel** [comment]
this bug is till in antd 2.6.4

**Comment by yiminghe** [comment]
we do not use browser-sync, but pr is welcomed
