### ISSUE TITLE
BUG:Key events on checkbox

### ISSUE THREAD

**Issue by BraisedChicken** [react-component/checkbox#203]
参考ant-design的这个issue [Key events on checkbox #27757](https://github.com/ant-design/ant-design/issues/27757#issue-742344078)

checkbox没有正确的调用相应的事件handler，可以直接查看 [这个](https://codesandbox.io/s/bold-kirch-s1p05?file=/src/App.js)

重现方法：同 ant-design的issue，点击input/RcCheckBox后，按下键盘按键。

**Comment by afc163** [comment]
来个 PR。
