### ISSUE TITLE
Does not work with browser-sync

### ISSUE THREAD

**Issue by kibao** [react-component/checkbox#21]
#19 broke support for browser-sync from #13

ref https://github.com/ant-design/ant-design/issues/2744

**Comment by ryannealmes** [comment]
Are there any updates on this? 

Is there a way around it. I can't get checkboxes working in my repo :/ What a rabbit hole this has been!

**Comment by ryannealmes** [comment]
I am trying to leverage this control in the react-slingshot framework.

It seems like a similar issue to this is cropping it's head up. I have forked the repo for slingshot and modified it to include the rc-checkbox control in the App component. If you do an npm install, npm start and try click the checkbox you will see that it doesn't change.

Any ideas on how to fix this? I have gone down this rabbit hole, but had no luck.

Happy to help out more if needed.

**Comment by markzhai** [comment]
Have the same issue here.

**Comment by kossel** [comment]
same issue :s have to disable browserSync snippet injection

**Comment by cleverjam** [comment]
are you guys working towards a fix with this issue?

**Comment by afc163** [comment]
It should be fixed at https://github.com/react-component/checkbox/commit/04a5d136406e595aac4bea4929a0694b5f8bb8ed, rc-checkbox@1.5.1
