### ISSUE TITLE
Bug: Defaulted props not used in onChange callback

### ISSUE THREAD

**Issue by chilled-capybara** [react-component/checkbox#230]
### Issue
The `props` that have default values, are not used in the `event.target` from `onChange`

### `v2.3.2` functionality
In `v2.3.2` the `props` were defaulted via `defaultProps`;

https://github.com/react-component/checkbox/blob/22992a52b8c4b7282fcb7df834298b1e2f87148e/src/index.jsx#L6-L18

Which meant that in the `onChange` `target` would use these defaulted props;
https://github.com/react-component/checkbox/blob/22992a52b8c4b7282fcb7df834298b1e2f87148e/src/index.jsx#L59-L63

### `v3.0.0` functionality
However in `v3.0.0`, the `props` are only defaulted in the destructuring;
https://github.com/react-component/checkbox/blob/cfdcf035085edf41f6204df44fd474160cee787a/src/index.tsx#L30-L40
Which means the defaulted values are not used for `target`;
https://github.com/react-component/checkbox/blob/cfdcf035085edf41f6204df44fd474160cee787a/src/index.tsx#L71-L75

### Summary

in `v2.3.2`; `<Checkbox onChange={(e) => console.log(e.target.type)} {...otherProps} />;` will log `"checkbox"`
in `v3.0.0`; `<Checkbox onChange={(e) => console.log(e.target.type)} {...otherProps} />;` will log `undefined`

**Comment by afc163** [comment]
PR is welcome~
