### ISSUE TITLE
Checkbox strips both synthetic & native event object off of all of their useful properties in `handleChange`

### ISSUE THREAD

**Issue by ddm-flipkart** [react-component/checkbox#30]
- Synthetic events are a superset of Native events and IMO Synthetic events should be preferred.
- Users wanting to use native events can always choose `event.nativeEvent`
- This code is suppressing both synthetic & native event object, which means `event.datasets` or `event.nativeEvent.target.dataset` can't be used anymore.
- This takes away the ability to access other DOM APIs even.

```js
this.props.onChange({
      target: {
        ...this.props,
        checked: e.target.checked,
      },
      stopPropagation() {
        e.stopPropagation();
      },
      preventDefault() {
        e.preventDefault();
      },
    });
```

**Comment by paranoidjk** [comment]
yep, we need to discuss about this. cc @yesmeck 

@yiminghe is aim to not access DOM, see https://github.com/react-component/checkbox/commit/33ab73a9818b4f624c60a88faea7ba723efe2c13

**Comment by paranoidjk** [comment]
https://github.com/react-component/slider/issues/261

**Comment by paranoidjk** [comment]
close since i think right now there is no necessary reason that we need expose native event.
