### ISSUE TITLE
onChange 传参 Event 而不直接是 checked 的原因？

### ISSUE THREAD

**Issue by nimojs** [react-component/checkbox#37]
请教一下

目前使用 Event 挺好的。我只是想请教作者们在回调时传递 Event 对象而不是直接传递 e.target.checked 的原因

```js
<Checkbox onChange={function(checked){

}} />
```

因为我在实现一些组件时会考虑如下2点：

- 传 Event 可维护性和适用场景更好
- 直接传 checked 所有组件 onChange 回调参数格式一致，能保持同一家族组件接口一致。

**Comment by nimojs** [comment]
ping~

**Comment by afc163** [comment]
可能没有考虑太多，就是对 `<input type="check" />` 的样式封装。

**Comment by nimojs** [comment]
了解了，谢谢
