### ISSUE TITLE
examples not working

### ISSUE THREAD

**Issue by jasonperk** [react-component/checkbox#5]
examples not working

http://react-component.github.io/checkbox/examples/simple.html

Uncaught Error: Cannot find module "rc-checkbox/assets/index.css"

**Comment by benjycui** [comment]
It is OK now, re-published.

**Comment by LiuuY** [comment]
http://react-component.github.io/checkbox/examples/simple.html

still not work.

chrome: Uncaught Error: Cannot find module "rc-checkbox/assets/index.css"
