### ISSUE TITLE
checkGroup参数共用

### ISSUE THREAD

**Issue by carlos121493** [react-component/checkbox#6]
如果有多组checkGroup会造成参数共用的情况

**Comment by benjycui** [comment]
Please read [CONTRIBUTING.md](https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md) first, and provide a demo, THX!

**Comment by TossShinHwa** [comment]
@benjycui [CONTRIBUTING.md](https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md) is missing.

**Comment by afc163** [comment]
Fixed in 7ce38e39b62be41021038f0d50f3000dfccfbdab

这个 issue 提错地方了。

ref #1101
